// <auto-generated />
using System;
using EnviosRapidosGT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnviosRapidosGT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("EnviosRapidosGT.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EnviosRapidosGT.Models.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoRastreo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntentosEntrega")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemitenteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("RemitenteId");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("EnviosRapidosGT.Models.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnvioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("EnviosRapidosGT.Models.Envio", b =>
                {
                    b.HasOne("EnviosRapidosGT.Models.Cliente", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnviosRapidosGT.Models.Cliente", "Remitente")
                        .WithMany()
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("EnviosRapidosGT.Models.HistorialEstado", b =>
                {
                    b.HasOne("EnviosRapidosGT.Models.Envio", null)
                        .WithMany("Historial")
                        .HasForeignKey("EnvioId");
                });

            modelBuilder.Entity("EnviosRapidosGT.Models.Envio", b =>
                {
                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
